backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"         # зураг хадгалах газар
public_folder: "/images/uploads"

media_library:
  name: "uploadcare"
  config:
    publicKey: "demopublickey"         # uploadcare ашиглахгүй бол энэ хэсгийг устгаж болно

collections:
  - name: "news"                       # фолдерын нэртэй адилхан байх
    label: "Мэдээнүүд"
    folder: "posts"                     # ✳️ GitHub дээрх хавтас (байх ёстой!)
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Гарчиг", name: "title", widget: "string" }
      - { label: "Огноо", name: "date", widget: "datetime" }
      - { label: "Агуулга", name: "body", widget: "markdown" }
