backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads" # Git дээр хадгалагдах зам
public_folder: "/images/uploads" # Вэбсайтад харагдах зам

media_library:
  name: uploadcare
  config:
    publicKey: demopublickey

collections:
  - name: "news"
    label: "Мэдээнүүд"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Гарчиг", name: "title", widget: "string" }
      - { label: "Огноо", name: "date", widget: "datetime" }
      - { label: "Агуулга", name: "body", widget: "markdown" }

